### ISSUE TITLE
support xhr requests in canduit and new api.token parameter

### ISSUE THREAD

**Issue by dswho** [uber/canduit#14]
The canduit api now appears to require a parameter `api.token` for requests.
Also on the client side requests a CSRF token is required and should be set in the header: `X-Phabricator-Csrf`.

I was able to figure out how to fix the issue by consulting these two pages:
https://secure.phabricator.com/P2028
https://secure.phabricator.com/T6661#85813

The validation for the csrf token appears to be in this [php controller.](https://github.com/phacility/phabricator/blob/6dea2ba3b37f0590efb607ea5e27c623ba19bca7/src/aphront/AphrontRequest.php#L310)

In the documentation for `maniphest.search` on `http://<your-phabricator.url>/conduit/method/maniphest.search/` the curl requests is documented as:
```bash
$ curl https://<your-phabricator.url>/api/maniphest.search \
    -d api.token=api-token \
    -d param=value \
    ...
```
## Reproduce Error
Login into phabricator and open the chrome developer console,
and then enter the following code and replace the template variables `<your-phabricator.url>` `<your-user.name>` with your appropriate values.
```javascript
// Get phabricator token:
// https://<your-phabricator.url>/settings/user/<your-user.name>/page/apitokens/
var phabricatorUrl = 'https://<your-phabricator.url>/'
var token = "token from https://<your-phabricator.url>/settings/user/<your-user.name>/page/apitokens/";
var data=`api.token=${token}`;

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", `${phabricatorUrl}/api/maniphest.search`);
xhr.setRequestHeader("content-type", "application/x-www-form-urlencoded");
xhr.setRequestHeader("cache-control", "no-cache");

xhr.send(data);
/* Here is the error in the logs.
{"result":null,"error_code":"ERR-CONDUIT-CORE","error_info":"You are trying to save some data to Phabricator, but the request your browser made included an incorrect token. Reload the page and try again. You may need to clear your cookies.\nThis was a Web request.\nThis request had no CSRF token."}
*/
```
<img width="1778" alt="screen shot 2018-08-22 at 2 32 18 pm" src="https://user-images.githubusercontent.com/22757012/44492121-40b79880-a618-11e8-89f8-ea17f7e3d8c5.png">

## Successful Request
```javascript
// Get phabricator token and csrf:
// Get your phabricator csrf token  from  'http://your.phabricator.url/login/refresh/'
// Copy paste the token in the request

var baseUrl = 'https://<your-phabricator.url>'
var token = "token form https://<your-phabricator.url>/settings/user/<your-user.name>/page/apitokens/";
var data = `api.token=${token}`;
var csrfToken = "token from http://<your.phabricator.url/>login/refresh/'"
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", `${baseUrl}/api/maniphest.search`);
xhr.setRequestHeader("content-type", "application/x-www-form-urlencoded");
xhr.setRequestHeader("cache-control", "no-cache");
/*X-Phabricator-Csrf is now set*/
xhr.setRequestHeader('X-Phabricator-Csrf', csrfToken);

xhr.send(data);
// You should see a list of maniphest tasks that match the search criteria
```

I'm currently working on a patch for this, but wanted to create this issue for more visibility.

The code that needs to be refactored is [`createRequest`](https://github.com/uber/canduit/blob/master/canduit.js#L114)

**Comment by dswho** [comment]
I verified that `api.token` is not a required parameter and the existing request setup does work, it's the csrf token that is still required:
Tested in javascript console in phabricator
```javascript
function testWithAlternateAPIToken(opts) {
  // instead of putting token in `api.token`, it can be put it in  `__conduit__[token]`.
  // get apiToken from https://<your-phabricator.url>/settings/user/<your-user.name>/page/apitokens/
  var apiToken = opts.apiToken;
  // Get your phabricator csrf token  from  'http://your.phabricator.url/login/refresh/'
  var csrfToken = opts.csrfToken;
  var baseURL = opts.baseURL;
  var data = new FormData();
  data.append("output", "json");
  data.append("params", "{\"constraints\":{\"statuses\":[\"open\"]},\"__conduit__\":{\"token\":\"" + apiToken + "\"}}");

  var xhr = new XMLHttpRequest();
  xhr.withCredentials = true;

  xhr.addEventListener("readystatechange", function () {
    if (this.readyState === 4) {
      console.log(this.responseText);
    }
  });

  xhr.open("POST", baseURL + "/api/maniphest.search");
  xhr.setRequestHeader("x-phabricator-csrf", csrfToken);
  xhr.setRequestHeader("cache-control", "no-cache");

  xhr.send(data);
}
 testWithAlternateAPIToken({
   apiToken: 'foo',
   csrfToken: 'bar',
   baseURL: 'https://your-phabricator.url'
});
```

**Comment by lxe** [comment]
The purpose of a CSRF token is to prevent a malicious party from making unauthorized requests (or tricking you into making requests). 

In the context of an API, I'm not quite sure why the conduit server requires a CSRF token. Outside of the browser context, XSRF doesn't make much sense, and canduit is not a browser client. 

You should be calling conduit API endpoints using the token obtained `~/.arcrc`

**Comment by dswho** [comment]
@lxe I'm working on patching a chrome extension that uses the canduit api as a browser client.

**Comment by lucasmarshall** [comment]
@lxe,

@dswho is fixing a phab plugin I wrote. Context: https://code.uberinternal.com/diffusion/COPHA/

**Comment by dswho** [comment]
closing this issue. Please refer to this comment: https://github.com/uber/canduit/pull/15#issuecomment-415568977
