### ISSUE TITLE
Canduit should fallback gracefully if HOME environment does not exist

### ISSUE THREAD

**Issue by crccheck** [uber/canduit#8]
I'm running a process that uses canduit in upstart, and I have no HOME, so I encountered:

    TypeError: Arguments to path.join must be strings

My workaround was to set HOME=/tmp for now. I can do a PR later.

**Comment by lxe** [comment]
You need to specify the `configFile` directly if it's impossible to find. I am making a fix that will still throw, but with a meaningful error.
